# Generated by Django 5.2.1 on 2025-09-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_avatar_remove_user_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AddField(
            model_name='user',
            name='club_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属社团'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='是否已认证'),
        ),
    ]
