# Generated by Django 5.2.1 on 2025-09-27 09:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='社团名称')),
                ('description', models.TextField(verbose_name='社团简介')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_clubs', to=settings.AUTH_USER_MODEL, verbose_name='社长')),
            ],
            options={
                'verbose_name': '社团',
                'verbose_name_plural': '社团',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('date', models.DateField(verbose_name='活动日期')),
                ('location', models.CharField(max_length=100, verbose_name='活动地点')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='club.club', verbose_name='所属社团')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'ordering': ['-date'],
            },
        ),
    ]
